### ISSUE TITLE
error TS7053: Element implicitly has an 'any' type because expression of type '"releasable"' can't be used to index type 'AvailabilityStatus'.   

### ISSUE THREAD

**Issue by aguluman** [domenichelfenstein/bike-rental-showcase#1]
Here are screenshots showing the errors when ever I run `npm run build`.

![Screenshot 2023-07-21 235253](https://github.com/domenichelfenstein/bike-rental-showcase/assets/56761791/3dafdc29-f801-4d3d-b05f-a33e11958135)
![Screenshot 2023-07-21 235500](https://github.com/domenichelfenstein/bike-rental-showcase/assets/56761791/d3dd72c9-b027-4914-bcb3-36d1f2607c69)
![Screenshot 2023-07-21 235649](https://github.com/domenichelfenstein/bike-rental-showcase/assets/56761791/e44eed0e-fec8-4ae9-a51f-98a64e23fd46)

What do you think could be the cause of it?

**Comment by domenichelfenstein** [comment]
You are right.
On `npm run build`, the TS linter detected an implicit `any`, which it doesn't like.
The code worked, but the linter wasn't satisfied.
I only ran `npm run dev` (as hinted in the readme) and therefore didn't recognize there was a linter error.

I made the code more type-safe and now the linter is happy. Thanks for bringing it up!

**Comment by aguluman** [comment]
Happy to help. 
Thank you for responding.

Can I ask what made you change from Angular to Vue, and why does most dotnet server use Angular on the client?
 

I'm @chukwuma_xx on twitter

**Comment by domenichelfenstein** [comment]
I had no particular reason which would apply for most folks. The reason was I had to give a frontend course for junior devs and it was decided to use Vue. So I thought I give it a try beforehand and use it in this project.

This being said, I quite like it:
This repo is meant as an architecture / sw design exercise and showcase. I like the way vue lets me easily integrate its components in my main (f#) structure and therefore have a well-arranged modular monolith.

As for your question of why Angular is often used alongside .net:
I simply don't know exactly. I can only speculate that Angular's object-oriented approach somehow resembles what many dotnet devs are used to from Razor or even WebForms. So it kinda integrates into the already established thought process of those devs.
Disclaimer: We use Angular in the app we actually work on and we don't hate it (it could always be better, of course).

**Comment by aguluman** [comment]
Thank you for this.

I'm learning your code base through the files you committed as you created the project.

I'm also reading the book. Domain Driven Design made functional with Fsharp by Scott Wlaschin. Its amazing. 

The codebase is looking a bit hard for me now, but as I dive deeper into the essential fsharp book I'm reading, it'll make more sense.

Just time will tell.
